
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dot-portal
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - laravelnet

networks:
  laravelnet:
    external: true
