<?php
namespace App\Mixins\Gateways;

use Omnipay\Omnipay;
use Exception;

class AuthnetGateway implements GatewayInterface
{
    
    public $params;
    public $gateway;
    public $response;
    public $transaction_id='';
    public $errors = [];
    public $success = false;
 
    public function __construct()
    {
        $this->gateway = Omnipay::create('AuthorizeNetApi_Api');
        $this->gateway->setAuthName(env('ANET_API_LOGIN_ID'));
        $this->gateway->setTransactionKey(env('ANET_TRANSACTION_KEY'));
        $this->gateway->setTestMode(true); //comment this line when move to 'live'
    }

    public function setParams($params)
    {
        $this->params = $params;
    }

    // https://github.com/thephpleague/omnipay
    public function charge()
    {
        try {

            // Set credit card
            $creditCard = $this->setCreditCard(); 

            $response = $this->gateway->purchase(
                array(
                    'amount' => $this->params['order_data']['amount'],
                    'currency' => $this->params['order_data']['currency'],
                    'card' => $creditCard
                ))->send();

            // Set global response
            $this->response = $response;

            // Process response
            $this->processResponse();

        } catch(Exception $e) {
            $this->setError( $e->getMessage() );
        }

    }

    private function setCreditCard()
    {
        return new \Omnipay\Common\CreditCard([
            'number' => $this->params['cart_data']['cc_number'],
            'expiryMonth' => $this->params['cart_data']['expiry_month'],
            'expiryYear' => $this->params['cart_data']['expiry_year'],
            'cvv' => $this->params['cart_data']['cvv'],
        ]);
    }

    private function processResponse()
    {
        /*
        $response->isSuccessful(); // is the response successful?
        $response->isRedirect(); // is the response a redirect?
        $response->getTransactionReference(); // a reference generated by the payment gateway
        $response->getTransactionId(); // the reference set by the originating website if available.
        $response->getMessage(); // a message generated by the payment gateway
        */

        // Retrieve data from response
        $this->transaction_id = $this->response->getData()['transactionResponse']['transId'];

        if( $this->response->isSuccessful() ) {    
            $this->success = true;
        } else {
            $this->setError( $this->response->getMessage() );
        }
    }

    private function makeTransactionId()
    {
        return time().rand(1, 999);
    }

    private function setError( $error )
    {
        $this->errors[] = $error;
    }

    public function getErrors()
    {
        return $this->errors;
    }

    public function isErrors()
    {
        return count($this->errors) > 0;
    }

    public function getResponse()
    {
        if( isset($this->response) ) {
            return $this->response->getData();
        } 
    }

    public function createSubscription()
    {
        try {
            $subscriptionData = [
                'amount'            => $this->params['subscription_data']['amount'],
                'currency'          => $this->params['subscription_data']['currency'],
                'intervalUnit'      => $this->params['subscription_data']['interval_unit'],
                'intervalLength'    => $this->params['subscription_data']['interval_length'],
                'startDate'         => $this->params['subscription_data']['start_date'],
                'totalOccurrences'  => $this->params['subscription_data']['total_occurrences'],
                'trialOccurrences'  => isset($this->params['subscription_data']['trial_occurrences']) ? $this->params['subscription_data']['trial_occurrences'] : 0,
                'card'              => new \Omnipay\Common\CreditCard([
                    'number'      => $this->params['cart_data']['cc_number'],
                    'expiryMonth' => $this->params['cart_data']['expiry_month'],
                    'expiryYear'  => $this->params['cart_data']['expiry_year'],
                    'cvv'         => $this->params['cart_data']['cvv'],
                ]),
            ];

            $response = $this->gateway->createSubscription($subscriptionData)->send();
            $this->response = $response;

            if ($response->isSuccessful()) {
                // Assuming the response contains a subscription ID
                $this->transaction_id = $response->getData()['subscriptionId'] ?? null;
                $this->success = true;
            } else {
                $this->setError($response->getMessage());
            }
        } catch(Exception $e) {
            $this->setError($e->getMessage());
        }
    }

    /**
     * Update an existing subscription
     *
     * @param string $subscriptionId The subscription identifier to update.
     * @param array $updateData The subscription fields to update (e.g., amount, interval, etc.)
     */
    public function updateSubscription($subscriptionId, $updateData)
    {
        try {
            // Add the subscription id to the update data array
            $updateData['subscriptionId'] = $subscriptionId;

            $response = $this->gateway->updateSubscription($updateData)->send();
            $this->response = $response;

            if ($response->isSuccessful()) {
                $this->success = true;
            } else {
                $this->setError($response->getMessage());
            }
        } catch(Exception $e) {
            $this->setError($e->getMessage());
        }
    }
    

}